import mongoose from "mongoose";

const payrollSchema = new mongoose.Schema({
  employee: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: "Employee", 
    required: [true, 'Employee reference is required']
  },
  payrollPeriod: {
    month: {
      type: Number,
      required: [true, 'Month is required'],
      min: [1, 'Month should be between 1-12'],
      max: [12, 'Month should be between 1-12']
    },
    year: {
      type: Number,
      required: [true, 'Year is required'],
      min: [2000, 'Year should be valid']
    }
  },
  workingDays: {
    totalDays: { 
      type: Number, 
      required: [true, 'Total working days is required'],
      min: [1, 'Total days should be at least 1']
    },
    presentDays: { 
      type: Number, 
      required: [true, 'Present days is required'],
      min: [0, 'Present days cannot be negative']
    },
    absentDays: {
      type: Number,
      default: 0,
      min: [0, 'Absent days cannot be negative']
    },
    leavesTaken: { 
      type: Number, 
      default: 0,
      min: [0, 'Leaves taken cannot be negative']
    },
    holidaysCount: {
      type: Number,
      default: 0,
      min: [0, 'Holidays count cannot be negative']
    },
    overtimeHours: {
      type: Number,
      default: 0,
      min: [0, 'Overtime hours cannot be negative']
    }
  },
  earnings: {
    basicSalary: {
      type: Number,
      required: [true, 'Basic salary is required'],
      min: [0, 'Basic salary cannot be negative']
    },
    hra: {
      type: Number,
      default: 0,
      min: [0, 'HRA cannot be negative']
    },
    allowances: {
      type: Number,
      default: 0,
      min: [0, 'Allowances cannot be negative']
    },
    overtimePay: {
      type: Number,
      default: 0,
      min: [0, 'Overtime pay cannot be negative']
    },
    bonus: {
      type: Number,
      default: 0,
      min: [0, 'Bonus cannot be negative']
    },
    incentives: {
      type: Number,
      default: 0,
      min: [0, 'Incentives cannot be negative']
    }
  },
  deductions: {
    providentFund: {
      type: Number,
      default: 0,
      min: [0, 'PF cannot be negative']
    },
    professionalTax: {
      type: Number,
      default: 0,
      min: [0, 'Professional tax cannot be negative']
    },
    incomeTax: {
      type: Number,
      default: 0,
      min: [0, 'Income tax cannot be negative']
    },
    esi: {
      type: Number,
      default: 0,
      min: [0, 'ESI cannot be negative']
    },
    loanDeduction: {
      type: Number,
      default: 0,
      min: [0, 'Loan deduction cannot be negative']
    },
    otherDeductions: {
      type: Number,
      default: 0,
      min: [0, 'Other deductions cannot be negative']
    },
    lateComingPenalty: {
      type: Number,
      default: 0,
      min: [0, 'Late coming penalty cannot be negative']
    },
    absentDeduction: {
      type: Number,
      default: 0,
      min: [0, 'Absent deduction cannot be negative']
    }
  },
  totalEarnings: {
    type: Number,
    required: true,
    min: [0, 'Total earnings cannot be negative']
  },
  totalDeductions: {
    type: Number,
    required: true,
    min: [0, 'Total deductions cannot be negative']
  },
  netSalary: { 
    type: Number, 
    required: [true, 'Net salary is required'],
    min: [0, 'Net salary cannot be negative']
  },
  status: { 
    type: String, 
    enum: {
      values: ["Draft", "Generated", "Approved", "Paid", "On Hold"],
      message: 'Status must be Draft, Generated, Approved, Paid, or On Hold'
    }, 
    default: "Generated" 
  },
  payDate: {
    type: Date,
    default: null
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: [true, 'Generated by is required']
  },
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  },
  approvedDate: {
    type: Date
  },
  paymentMethod: {
    type: String,
    enum: ["bank_transfer", "cash", "cheque"],
    default: "bank_transfer"
  },
  paymentReference: {
    type: String
  },
  remarks: {
    type: String,
    maxlength: [300, 'Remarks cannot exceed 300 characters']
  },
  isRevised: {
    type: Boolean,
    default: false
  },
  revisionHistory: [{
    revisedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User"
    },
    revisedDate: {
      type: Date,
      default: Date.now
    },
    reason: String,
    previousNetSalary: Number
  }]
}, { 
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Compound index to prevent duplicate payroll for same employee in same month
payrollSchema.index({ 
  employee: 1, 
  'payrollPeriod.month': 1, 
  'payrollPeriod.year': 1 
}, { unique: true });

// Other indexes for faster queries
payrollSchema.index({ status: 1 });
payrollSchema.index({ generatedBy: 1 });
payrollSchema.index({ 'payrollPeriod.year': 1, 'payrollPeriod.month': 1 });

// Virtual for payroll period string
payrollSchema.virtual('payrollPeriodString').get(function() {
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
  ];
  return `${months[this.payrollPeriod.month - 1]}-${this.payrollPeriod.year}`;
});

// Virtual for attendance percentage
payrollSchema.virtual('attendancePercentage').get(function() {
  if (this.workingDays.totalDays === 0) return 0;
  return ((this.workingDays.presentDays / this.workingDays.totalDays) * 100).toFixed(2);
});

// Pre-save middleware to calculate totals
payrollSchema.pre('save', function(next) {
  // Calculate total earnings
  this.totalEarnings = 
    this.earnings.basicSalary + 
    this.earnings.hra + 
    this.earnings.allowances + 
    this.earnings.overtimePay + 
    this.earnings.bonus + 
    this.earnings.incentives;
  
  // Calculate total deductions
  this.totalDeductions = 
    this.deductions.providentFund + 
    this.deductions.professionalTax + 
    this.deductions.incomeTax + 
    this.deductions.esi + 
    this.deductions.loanDeduction + 
    this.deductions.otherDeductions + 
    this.deductions.lateComingPenalty + 
    this.deductions.absentDeduction;
  
  // Calculate net salary
  this.netSalary = Math.max(0, this.totalEarnings - this.totalDeductions);
  
  // Set pay date when status changes to paid
  if (this.isModified('status') && this.status === 'Paid' && !this.payDate) {
    this.payDate = new Date();
  }
  
  next();
});

// Static method to generate payroll for an employee
payrollSchema.statics.generatePayrollForEmployee = async function(employeeId, month, year, generatedBy) {
  const Employee = mongoose.model('Employee');
  const Attendance = mongoose.model('Attendance');
  
  // Get employee details
  const employee = await Employee.findById(employeeId).populate('user');
  if (!employee) {
    throw new Error('Employee not found');
  }
  
  // Calculate working days for the month
  const daysInMonth = new Date(year, month, 0).getDate();
  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month - 1, daysInMonth);
  
  // Get attendance data for the month
  const attendanceData = await Attendance.find({
    employee: employeeId,
    date: { $gte: startDate, $lte: endDate }
  });
  
  // Calculate attendance summary
  const presentDays = attendanceData.filter(att => att.status === 'Present').length;
  const absentDays = attendanceData.filter(att => att.status === 'Absent').length;
  const leavesTaken = attendanceData.filter(att => att.status === 'Leave').length;
  const holidaysCount = attendanceData.filter(att => att.status === 'Holiday').length;
  const totalOvertimeHours = attendanceData.reduce((sum, att) => sum + (att.overtimeHours || 0), 0);
  
  // Calculate pro-rated salary based on attendance
  const attendanceRatio = presentDays / daysInMonth;
  const basicSalary = employee.salary.basic * attendanceRatio;
  const hra = employee.salary.hra * attendanceRatio;
  const allowances = employee.salary.allowance * attendanceRatio;
  
  // Calculate overtime pay (assuming hourly rate is basic salary / (8 hours * working days))
  const hourlyRate = employee.salary.basic / (8 * 22); // Assuming 22 working days
  const overtimePay = totalOvertimeHours * hourlyRate * 1.5; // 1.5x for overtime
  
  // Calculate deductions
  const providentFund = employee.salary.providentFund || (basicSalary * 0.12); // 12% PF
  const professionalTax = employee.salary.professionalTax || 200;
  const incomeTax = employee.salary.incomeTax || 0;
  
  // Calculate absent deduction
  const absentDeduction = absentDays * (employee.salary.basic / daysInMonth);
  
  const payrollData = {
    employee: employeeId,
    payrollPeriod: { month, year },
    workingDays: {
      totalDays: daysInMonth,
      presentDays,
      absentDays,
      leavesTaken,
      holidaysCount,
      overtimeHours: totalOvertimeHours
    },
    earnings: {
      basicSalary,
      hra,
      allowances,
      overtimePay,
      bonus: 0,
      incentives: 0
    },
    deductions: {
      providentFund,
      professionalTax,
      incomeTax,
      esi: 0,
      loanDeduction: 0,
      otherDeductions: 0,
      lateComingPenalty: 0,
      absentDeduction
    },
    generatedBy
  };
  
  return new this(payrollData);
};

export default mongoose.model("Payroll", payrollSchema);